//items desabilitados By SrNadien
ServerEvents.recipes(nadien => {

    nadien.remove({output: [
        'avaritia:extreme_crafting_table',
        'avaritia:endless_cake',
        'avaritia:star_fuel',
        'twilightforest:uncrafting_table',
        "avaritia:diamond_lattice",
        'avaritia:copper_singularity',
        'avaritia:double_compressed_crafting_table',
        'avaritia:compressed_crafting_table',
        'avaritia:neutronium_compressor',
        'reliquary:magicbane',
        'apotheosis:gem',
        'industrialforegoing:hydroponic_bed',
        'angelring:resonant_angel_ring',
        'expandedstorage:diamond_to_netherite_conversion_kit',
        'expandedstorage:gold_to_diamond_conversion_kit',
        'expandedstorage:wood_to_iron_conversion_kit',
        'expandedstorage:wood_to_diamond_conversion_kit',
        'expandedstorage:wood_to_gold_conversion_kit',
        'expandedstorage:copper_to_netherite_conversion_kit',
        'expandedstorage:copper_to_diamond_conversion_kit',
        'expandedstorage:iron_to_diamond_conversion_kit',
        'expandedstorage:copper_to_gold_conversion_kit',
        'majruszsdifficulty:pillager_treasure_bag',
        'expandedstorage:obsidian_to_netherite_conversion_kit', 
        'expandedstorage:wood_to_copper_conversion_kit',
        'expandedstorage:gold_to_netherite_conversion_kit',
        'expandedstorage:iron_to_netherite_conversion_kit',
        'expandedstorage:gold_to_obsidian_conversion_kit',
        'expandedstorage:iron_to_obsidian_conversion_kit',
        'expandedstorage:iron_to_gold_conversion_kit',
        'expandedstorage:copper_to_obsidian_conversion_kit',
        'expandedstorage:netherite_chest_minecart',
        'expandedstorage:obsidian_chest_minecart',
        'mekanism:personal_barrel',
        'expandedstorage:present_minecart',
        'alltheores:iron_ore_hammer',
        'apotheosis:simple_reforging_table',
        'expandedstorage:pumpkin_chest',
        'expandedstorage:waxed_exposed_copper_mini_barrel',
        'apotheosis:vial_of_unnaming',
        'alltheores:copper_ore_hammer',
       'alltheores:invar_ore_hammer',
        'expandedstorage:pumpkin_chest_minecart',
        'apotheosis:vial_of_extraction',
        'apotheosis:vial_of_expulsion',
        'ftbquests:stage_barrier',
        'expandedstorage:diamond_chest_minecart',
        'expandedstorage:diamond_mini_chest',
       'expandedstorage:gold_chest_minecart',
       'expandedstorage:exposed_copper_mini_barrel',
       'expandedstorage:wood_chest_minecart',
       'majruszsdifficulty:warden_treasure_bag',
       'ftbquests:barrier',
       'expandedstorage:netherite_mini_barrel',
       'expandedstorage:moss_chest_minecart',
       'expandedstorage:iron_chest_minecart',
       'alltheores:bronze_ore_hammer',
       'expandedstorage:white_mini_present',
       'expandedstorage:gold_chest',
       'expandedstorage:mini_barrel',
        'extendedcrafting:compressor',
        'avaritia:dense_neutron_collector',
        'avaritia:denser_neutron_collector',
        'avaritia:eternal_singularity',
        'evilcraft:spirit_furnace',
        'expandedstorage:copper_barrel', 
        'expandedstorage:exposed_copper_barrel', 
        'expandedstorage:weathered_copper_barrel', 
        'expandedstorage:oxidized_copper_barrel', 
        'expandedstorage:waxed_copper_barrel', 
        'expandedstorage:waxed_exposed_copper_barrel', 
        'expandedstorage:waxed_weathered_copper_barrel', 
        'expandedstorage:waxed_oxidized_copper_barrel', 
        'expandedstorage:iron_barrel', 
        'expandedstorage:gold_barrel', 
        'expandedstorage:diamond_barrel', 
        'expandedstorage:obsidian_barrel', 
        'expandedstorage:netherite_barrel',
        'allthemodium:teleport_pad'
    ]
    })









})
