#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=ring;size=8;operation=ADD;add_cosmetic=true", "id=belt;size=4;operation=ADD;add_cosmetic=true", "id=amulet;size=2;operation=ADD;add_cosmetic=true", "id=necklace;size=4;operation=ADD;add_cosmetic=true", "id=bracelet;size=2;operation=ADD;add_cosmetic=true", "id=curio;size=5;operation=ADD;add_cosmetic=true", "id=charm;size=3;operation=ADD;add_cosmetic=true", "id=back;size=2;operation=ADD;add_cosmetic=true", "id=bundle;size=2;operation=REMOVE;add_cosmetic=false"]

